services:

  openclaw:
    build: ./gateway/openclaw
    ports:
      - "18789:18789"
    command:
      [
        "node",
        "openclaw.mjs",
        "gateway",
        "--bind",
        "lan",
        "--allow-unconfigured"
      ]
    environment:
      gateway__controlUi__allowedOrigins: "*"

  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - openclaw